spring:
  application:
    name: T-Learn-App
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/t-learn}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
  liquibase:
    enabled: false

jobs:
  StatQueueJob:
    enabled: true
    cron: "0 0 0 * * *"
    batch-size: 100
    iteration-size: 50